gamecard : Conexion_con_broker.c Conexion_con_gameboy.c Contexto_gameCard.c FileSystem.c formatoFs.c Funciones_de_conexion.c Herramientas_gameCard.c mensajesParaFs.c gameCard.c
	mkdir -p ./Debug ./Dist /home/utnso/desktop/tall-grass
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Contexto_broker.d" -MT"./Conexion_con_broker.o" -o "./Debug/Conexion_con_broker.o" "./Conexion_con_broker.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Conexion_con_gameboy.d" -MT"Conexion_con_gameboy.o" -o "./Debug/Conexion_con_gameboy.o" "./Conexion_con_gameboy.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Contexto_gameCard.d" -MT"Contexto_gameCard.o" -o "./Debug/Contexto_gameCard.o" "./Contexto_gameCard.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/FileSystem.d" -MT"./FileSystem.o" -o "./Debug/FileSystem.o" "./FileSystem.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/formatoFs.d" -MT"formatoFs.o" -o "./Debug/formatoFs.o" "./formatoFs.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Funciones_de_conexion.d" -MT"./Funciones_de_conexion.o" -o "./Debug/Funciones_de_conexion.o" "./Funciones_de_conexion.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Herramientas_gameCard.d" -MT"./Herramientas_gameCard.o" -o "./Debug/Herramientas_gameCard.o" "./Herramientas_gameCard.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/mensajesParaFs.d" -MT"./mensajesParaFs.o" -o "./Debug/mensajesParaFs.o" "./mensajesParaFs.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/gameCard.d" -MT"./gameCard.o" -o "./Debug/gameCard.o" "./gameCard.c"
	gcc -L"../Pokebola/Debug" -o "./Dist/gamecard" ./Debug/Conexion_con_broker.o ./Debug/Conexion_con_gameboy.o  ./Debug/Contexto_gameCard.o ./Debug/FileSystem.o ./Debug/formatoFs.o ./Debug/Funciones_de_conexion.o ./Debug/Herramientas_gameCard.o ./Debug/mensajesParaFs.o ./Debug/gameCard.o   -lPokebola -lcommons -lpthread

clean :
	rm -f ./Dist/gameCard ./Debug/*

all:  Conexion_con_broker.c Conexion_con_gameboy.c Contexto_gameCard.c FileSystem.c formatoFs.c Funciones_de_conexion.c Herramientas_gameCard.c mensajesParaFs.c gameCard.c
	mkdir -p ./Debug ./Dist /home/utnso/desktop/tall-grass
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Contexto_broker.d" -MT"./Conexion_con_broker.o" -o "./Debug/Conexion_con_broker.o" "./Conexion_con_broker.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Conexion_con_gameboy.d" -MT"Conexion_con_gameboy.o" -o "./Debug/Conexion_con_gameboy.o" "./Conexion_con_gameboy.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Contexto_gameCard.d" -MT"Contexto_gameCard.o" -o "./Debug/Contexto_gameCard.o" "./Contexto_gameCard.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/FileSystem.d" -MT"./FileSystem.o" -o "./Debug/FileSystem.o" "./FileSystem.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/formatoFs.d" -MT"formatoFs.o" -o "./Debug/formatoFs.o" "./formatoFs.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Funciones_de_conexion.d" -MT"./Funciones_de_conexion.o" -o "./Debug/Funciones_de_conexion.o" "./Funciones_de_conexion.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Herramientas_gameCard.d" -MT"./Herramientas_gameCard.o" -o "./Debug/Herramientas_gameCard.o" "./Herramientas_gameCard.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/mensajesParaFs.d" -MT"./mensajesParaFs.o" -o "./Debug/mensajesParaFs.o" "./mensajesParaFs.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/gameCard.d" -MT"./gameCard.o" -o "./Debug/gameCard.o" "./gameCard.c"
	gcc -L"../Pokebola/Debug" -o "./Dist/gamecard" ./Debug/Conexion_con_broker.o ./Debug/Conexion_con_gameboy.o  ./Debug/Contexto_gameCard.o ./Debug/FileSystem.o ./Debug/formatoFs.o ./Debug/Funciones_de_conexion.o ./Debug/Herramientas_gameCard.o ./Debug/mensajesParaFs.o ./Debug/gameCard.o -lpokebola -lcommons -lpthread