Team : Team.c Contexto_team.c Herramientas_team.c
	gcc -I"/home/utnso/workspace/tp-2020-1c-eevee/Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"Contexto_team.d" -MT"Contexto_team.o" -o "Contexto_team.o" "./Contexto_team.c"
	gcc -I"/home/utnso/workspace/tp-2020-1c-eevee/Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"Herramientas_team.d" -MT"Herramientas_team.o" -o "Herramientas_team.o" "./Herramientas_team.c"
	gcc -I"/home/utnso/workspace/tp-2020-1c-eevee/Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"Team.d" -MT"Team.o" -o "Team.o" "./Team.c"
	gcc -L"/home/utnso/workspace/tp-2020-1c-eevee/Pokebola/Debug" -o "TEAM"  ./Contexto_team.o ./Herramientas_team.o ./Team.o   -lPokebola -lcommons
