Team : Contexto_team.c Herramientas_team.c Deadlock.c Algoritmos_de_planificacion.c Entrenador.c Funciones_de_conexion.c Funciones_para_listas.c Interaccion_con_broker.c Interaccion_con_gameboy.c Team.c
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../Pokebola/Debug
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Contexto_team.d" -MT"./Contexto_team.o" -o "./Debug/Contexto_team.o" "./Contexto_team.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Herramientas_team.d" -MT"Herramientas_team.o" -o "./Debug/Herramientas_team.o" "./Herramientas_team.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Deadlock.d" -MT"Deadlock.o" -o "./Debug/Deadlock.o" "./Deadlock.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Algoritmos_de_planificacion.d" -MT"./Algoritmos_de_planificacion.o" -o "./Debug/Algoritmos_de_planificacion.o" "./Algoritmos_de_planificacion.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Entrenador.d" -MT"Entrenador.o" -o "./Debug/Entrenador.o" "./Entrenador.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Funciones_de_conexion.d" -MT"./Funciones_de_conexion.o" -o "./Debug/Funciones_de_conexion.o" "./Funciones_de_conexion.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Funciones_para_listas.d" -MT"./Funciones_para_listas.o" -o "./Debug/Funciones_para_listas.o" "./Funciones_para_listas.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Interaccion_con_broker.d" -MT"./Interaccion_con_broker.o" -o "./Debug/Interaccion_con_broker.o" "./Interaccion_con_broker.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Interaccion_con_gameboy.d" -MT"./Interaccion_con_gameboy.o" -o "./Debug/Interaccion_con_gameboy.o" "./Interaccion_con_gameboy.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Team.d" -MT"./Team.o" -o "./Debug/Team.o" "./Team.c"
	gcc -L"../Pokebola/Debug" -o "./Dist/team" ./Debug/Contexto_team.o ./Debug/Herramientas_team.o ./Debug/Deadlock.o ./Debug/Algoritmos_de_planificacion.o  ./Debug/Entrenador.o ./Debug/Funciones_de_conexion.o ./Debug/Funciones_para_listas.o ./Debug/Interaccion_con_broker.o ./Debug/Interaccion_con_gameboy.o ./Debug/Team.o   -lPokebola -lcommons -lpthread

clean :
	rm -f ./Dist/team ./Dist/log_team ./Dist/team.log ./Debug/*

all : Contexto_team.c Herramientas_team.c Deadlock.c Algoritmos_de_planificacion.c Entrenador.c Funciones_de_conexion.c Funciones_para_listas.c Interaccion_con_broker.c Interaccion_con_gameboy.c Team.c
	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../Pokebola/Debug
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Contexto_team.d" -MT"./Contexto_team.o" -o "./Debug/Contexto_team.o" "./Contexto_team.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Herramientas_team.d" -MT"Herramientas_team.o" -o "./Debug/Herramientas_team.o" "./Herramientas_team.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Deadlock.d" -MT"Deadlock.o" -o "./Debug/Deadlock.o" "./Deadlock.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Algoritmos_de_planificacion.d" -MT"./Algoritmos_de_planificacion.o" -o "./Debug/Algoritmos_de_planificacion.o" "./Algoritmos_de_planificacion.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Entrenador.d" -MT"Entrenador.o" -o "./Debug/Entrenador.o" "./Entrenador.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Funciones_de_conexion.d" -MT"./Funciones_de_conexion.o" -o "./Debug/Funciones_de_conexion.o" "./Funciones_de_conexion.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Funciones_para_listas.d" -MT"./Funciones_para_listas.o" -o "./Debug/Funciones_para_listas.o" "./Funciones_para_listas.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Interaccion_con_broker.d" -MT"./Interaccion_con_broker.o" -o "./Debug/Interaccion_con_broker.o" "./Interaccion_con_broker.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Interaccion_con_gameboy.d" -MT"./Interaccion_con_gameboy.o" -o "./Debug/Interaccion_con_gameboy.o" "./Interaccion_con_gameboy.c"
	gcc -I"../Pokebola" -Icommons -IPokebola -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"./Debug/Team.d" -MT"./Team.o" -o "./Debug/Team.o" "./Team.c"
	gcc -L"../Pokebola/Debug" -o "./Dist/team" ./Debug/Contexto_team.o ./Debug/Herramientas_team.o ./Debug/Deadlock.o ./Debug/Algoritmos_de_planificacion.o  ./Debug/Entrenador.o ./Debug/Funciones_de_conexion.o ./Debug/Funciones_para_listas.o ./Debug/Interaccion_con_broker.o ./Debug/Interaccion_con_gameboy.o ./Debug/Team.o   -lPokebola -lcommons -lpthread

